### PR TITLE
Automation improvements

### PR DESCRIPTION
**Pull request by zain-sohail**

### CODE REVIEW

**Comment by zain-sohail** [comment]
closes #279

**Comment by rettigl** [comment]
The workflows should also run if one updates the workflow files...

**Comment by zain-sohail** [comment]
> The workflows should also run if one updates the workflow files...

Shouldn't be the case. The workflows don't check or do anything with the workflow files. Most of our workflows are based on checking sed or tests folder (so they can be further restricted). And documentation is based on sed and tutorial. Build is based on toml and sed.

If you mean we should be able to test the workflows, I'd suggest we add a manual run option.

**Comment by rettigl** [comment]
What I mean is that a workflow should run if itself is being updated. Today, the documentation workflow was broken, and it did not run when I fixed it.

**Comment by zain-sohail** [comment]
I get that. I can add for each workflow this option. 

Currently pytest and pylint run on all pushes. Shall that also be restricted to certain folders?

**Pull request merged**
