### PR TITLE
Flash energy calibration

### PR DESCRIPTION
**Pull request by rettigl**
This PR is for developing energy calibration methods for flash. 
So far, it contains an example notebook on how to load the provided FLASH energy calibration run into the existing energy calibration workflow in the processor, and demonstrates how to use the existing energy calibration functions.

### CODE REVIEW

**Comment by steinnymir** [comment]
What are the changes introduced is this PR?
should I merge them into #169 where we are developing hextof related calibrations and corrections?

**Comment by rettigl** [comment]
It contains the energy calibration notebook by dima, which I modified to use the methods from mpes to optain the parameters, and do the energy calibration. For this I had to also modify the code somewhat to allow ingesting the bias series data from externally binned arrays, rather than only binning internally. This was on the agenda anyways.
The notebook could either stay a tutorial notebook, or be removed, otherwise this could be merged to main, as it closes #146.
It also provides a first demonstrator for #102, albeit without the energy shift by bias/photon energy, etc, and potential changes you might want to introduce.

**Comment by rettigl** [comment]
It might not be a good tutorial notebook, as the data are not publically available. We could upate it with the now-available public data.

**Comment by steinnymir** [comment]
ok, so these changes will be necessary to run the energy calibration functions.
I would merge this in #169 then. is this tested and ready to go?

**Comment by rettigl** [comment]
Apart from the notebook, this is has tests and works. It's a small change. As I said, after review can be merged to main to close #146 and then rebase #169, that would be my preferred way

**Review by steinnymir — APPROVED** [review]

**Comment by steinnymir** [comment]
Can we merge this PR so I can implement it in #169 ?

**Pull request merged**
