### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by zainsohail04**

### CODE REVIEW

**Comment by steinnymir** [comment]
This looks nice, if it does what I think!
Is it ready to go or does it need more tweaking?

**Comment by zainsohail04** [comment]
> This looks nice, if it does what I think! Is it ready to go or does it need more tweaking?

Yea these are just templates for bugs or feature requests. I think the default is quite usable.

**Comment by steinnymir** [comment]
is there a reason why this removes the tutorial folder and content? How is it related to the issue templates? @zainsohail04

**Comment by zainsohail04** [comment]
> is there a reason why this removes the tutorial folder and content? How is it related to the issue templates? @zainsohail04

Should be part of #53. If it deletes the tutorial, we can always add it back

**Pull request merged**
