### PR TITLE
Mpes process files from memory

### PR DESCRIPTION
**Pull request by rettigl**
Processing directly from the files for mpes is rather slow if reading from a filesystem with poor seeking performance (e.g. hdd, network drives). To overcome this, we load all files completely into memory for each binning step, and then access them from there.

### CODE REVIEW

**Comment by rettigl** [comment]
@zain-sohail, this is mpes-specific, maybe you can give it a brief look and commend/approve?

**Comment by zain-sohail** [comment]
would this still work with smaller memory setups?

**Comment by rettigl** [comment]
> would this still work with smaller memory setups?

We are talking about additional ~100 mbyte memory per compute core, compared to several GByte for the actual binning volume, so typically only an increase of 10% or less in memory consumption. You can always compensate with using less cores if memory is an issue.

**Review by zain-sohail — APPROVED** [review]
Tested. LGTM!

**Pull request merged**
